// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAIMdUitefYN5pxqvs7xQnF6YH0tu7dkTo',
    appId: '1:284176263122:web:c62977ca433fae93aa0a0b',
    messagingSenderId: '284176263122',
    projectId: 'visiontubeapp',
    authDomain: 'visiontubeapp.firebaseapp.com',
    storageBucket: 'visiontubeapp.appspot.com',
    measurementId: 'G-5BPE2QYYQ1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA0fPa7J4LydGN5t0VDp_8kamS7PlPTJes',
    appId: '1:284176263122:android:c891d1d5d8c66c87aa0a0b',
    messagingSenderId: '284176263122',
    projectId: 'visiontubeapp',
    storageBucket: 'visiontubeapp.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAF4adPwxyWVfjmtbApD3tJKG8yDEtle0k',
    appId: '1:284176263122:ios:ff96a6dac05b959eaa0a0b',
    messagingSenderId: '284176263122',
    projectId: 'visiontubeapp',
    storageBucket: 'visiontubeapp.appspot.com',
    iosClientId: '284176263122-k46rouu28t8pin89i6cdf59gsbeij44k.apps.googleusercontent.com',
    iosBundleId: 'com.example.visiontube',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAF4adPwxyWVfjmtbApD3tJKG8yDEtle0k',
    appId: '1:284176263122:ios:5dc79b629f9c0622aa0a0b',
    messagingSenderId: '284176263122',
    projectId: 'visiontubeapp',
    storageBucket: 'visiontubeapp.appspot.com',
    iosClientId: '284176263122-bmg2mdacd0h8mrugl2fng194k7hnlt7i.apps.googleusercontent.com',
    iosBundleId: 'com.example.visiontube.RunnerTests',
  );
}
